# Generated by Django 3.2.8 on 2021-10-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AspectActlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitycode', models.CharField(max_length=16)),
                ('comment', models.CharField(max_length=256)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'aspect_actlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AspectErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorcode', models.CharField(max_length=16)),
                ('comment', models.CharField(max_length=256)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'aspect_errors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AspectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
                ('type', models.CharField(max_length=32)),
                ('version', models.IntegerField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'aspect_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AspectLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=16)),
                ('graphname', models.CharField(max_length=256)),
                ('currentversion', models.IntegerField()),
                ('auth_user_id', models.PositiveIntegerField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'aspect_lookup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('sourcecode', models.CharField(max_length=16, null=True)),
                ('source', models.CharField(default='', max_length=64)),
                ('sourceurl', models.CharField(default='', max_length=256)),
                ('datasetname', models.CharField(max_length=16, null=True)),
                ('uniqueidformat', models.CharField(max_length=128, null=True)),
                ('protected', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=16)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'datasets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacetActlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitycode', models.CharField(max_length=16)),
                ('comment', models.CharField(max_length=256)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'facet_actlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacetErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorcode', models.CharField(max_length=16)),
                ('comment', models.CharField(max_length=256)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'facet_errors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacetFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
                ('type', models.CharField(max_length=32)),
                ('version', models.IntegerField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'facet_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacetLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=16)),
                ('graphname', models.CharField(max_length=256)),
                ('currentversion', models.IntegerField()),
                ('auth_user_id', models.PositiveIntegerField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'facet_lookup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JsonActlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default=None, max_length=24)),
                ('activitylog', models.CharField(default='', max_length=2048)),
                ('comment', models.CharField(default=None, max_length=256)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'json_actlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JsonAspects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'json_aspects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JsonErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default=None, max_length=24)),
                ('errorcode', models.CharField(default='', max_length=128)),
                ('comment', models.CharField(default=None, max_length=256)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'json_errors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JsonFacets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'json_facets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JsonFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(default='')),
                ('type', models.CharField(default='', max_length=32)),
                ('version', models.IntegerField(default='')),
                ('jhash', models.CharField(blank=True, max_length=52, null=True)),
                ('comments', models.CharField(blank=True, max_length=32, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'json_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JsonLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(default='', max_length=128, unique=True)),
                ('title', models.CharField(default='', max_length=256)),
                ('graphname', models.CharField(default='', max_length=256)),
                ('currentversion', models.IntegerField(default=0)),
                ('auth_user_id', models.IntegerField(default='')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'json_lookup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('journal', models.CharField(blank=True, max_length=256, null=True)),
                ('authors', models.CharField(blank=True, max_length=2048, null=True)),
                ('aulist', models.CharField(blank=True, max_length=1024, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=12, null=True)),
                ('issue', models.CharField(blank=True, max_length=16, null=True)),
                ('startpage', models.CharField(blank=True, max_length=16, null=True)),
                ('endpage', models.CharField(blank=True, max_length=16, null=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('doi', models.CharField(max_length=256)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'references',
                'managed': False,
            },
        ),
    ]
