# Generated by Django 4.1.4 on 2022-12-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonLookupSubstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'json_lookup_substances',
                'managed': False,
            },
        ),
    ]
